### ISSUE TITLE
Spike Traps Not Working

### ISSUE THREAD

**Issue by Liham** [AI-Productions/AndOre#185] opened 2016-09-16 17:21 UTC
Team: QA Team

Date: 9/16/16

Description of Bug: I found three spike traps in a row that were surrounded on three sides by fences. I tried to walk on them to see how much damage they did, but I could only stand on one of them. 
Image:
![capture](https://cloud.githubusercontent.com/assets/22137914/18594717/4f6fa2c6-7c0f-11e6-8979-8e435dd92024.PNG)

How to replicate: Put three spike traps in a row (not column but that might cause the bug also), and surround them on all sides, but one, in fences.

Other relevant info: The spike traps were neutral, not enemy, when I tried to stand on them. Also, I wasn't part of a corporation when I tried to stand on the traps.

**Comment by JCharante** [comment] 2016-09-18 21:28
This bug is caused by the Order of Renderations in https://github.com/baxter-cs/AndOre/blob/master/server/cell.py#L137

As you can see, it checks to see if a spiketrap is there before if a fence is there, and due build-able sharing the same flag as passable, (seen in https://github.com/baxter-cs/AndOre/issues/119) someone built a fence on top of the spiketrap. Sorry for the late reply, but I know exactly what caused this as soon as I saw the screenshot (so thank you for providing it). You can text it out by first building a spiketrap and then building a fence on it.

**Comment by JCharante** [comment] 2016-11-12 13:15
Fixed in https://github.com/AI-Productions/AndOre/pull/226

**Closed by JCharante** 2016-11-12 13:15 UTC
Labels: bug, bug located
