### ISSUE TITLE
Factory not colored

### ISSUE THREAD

**Issue by reverse-flash1234** [AI-Productions/AndOre#196] opened 2016-09-30 17:24 UTC
Factory showed up as neutral, not as a corp member color.

**Comment by JCharante** [comment] 2016-10-04 00:43
What isn't showing color? Please include some form of screenshot and follow the bug report format.

**Comment by reverse-flash1234** [comment] 2016-10-04 01:06
The factory wasn't showing up green it was still black

**Comment by JCharante** [comment] 2016-11-28 19:53
Haven't been able to replicate due to lack of replication instructions, and I've rewritten the code that renders the world so I'm going to close this issue.

**Closed by JCharante** 2016-11-28 19:53 UTC

**Comment by TheCoub** [comment] 2016-11-28 19:56
It is worth noting that proper replication of the bug requires 3 or 4 people, and proper instructions are hard to give as the exact causes are still not completely known. To check exact causes, we would need to be able to leave our current corps so we are able to mess around with exactly what causes the bug.

**Comment by JCharante** [comment] 2016-11-28 19:57
It should be easier to find the cause of it, due to the separation of what the server sends and what the client renders thanks to Bengal
